Enhancement/addcatchallroute
CouncilDataProject/cdp-frontend pull request #223
Opened 2022-05-25 21:05 UTC by NeelApte

### Link to Relevant Issue

This pull request resolves #102 

### Description of Changes

Displays an error message when the route given is not provided. Also provides a general error page for future development. 

### Link to Site

https://neelapte.github.io/cdp-frontend/#/9999

This page displays a page not found error. 

https://neelapte.github.io/cdp-frontend/#/events/8888

This page displays a formatted error. 

_Please see `CONTRIBUTING.md` for directions on how this can be done._

2022-05-25 21:49 UTC, tohuynh requested changes
Looks good. I have few minor asks for the styling.

Just a heads up regarding git history. Your local `main` should contain only peer-reviewed code. Meaning you shouldn't merge local changes to your local `main` branch. Instead, you can get the latest changes from upstream (this repo)'s `main` branch if you need to resolve a merge conflict. This way you can keep the commit history of the PR clean (e.g. it wouldn't include your Underline commit in this PR).

2022-05-25 21:49 UTC, tohuynh commented on src/app/App.tsx
> +import ErrorPage from "../pages/ErrorPage/ErrorPage";
Change to
```
import { ErrorPage } from "../pages/ErrorPage";
```

for consistent imports

2022-05-25 21:49 UTC, tohuynh commented on src/app/App.tsx
> +                <Route component={ErrorPage} />
Add a `<Route path="*" component={ErrorPage} />` as recommended by the [react-router doc](https://v5.reactrouter.com/web/example/no-match).

2022-05-25 21:49 UTC, tohuynh commented on src/pages/ErrorPage/ErrorPage.tsx
> +      <button onClick={() => history.goBack()}>Back</button>
I think the content of h1 should always be "Sorry, we can’t find that page." The h1 should have className="mzp-u-title-sm" to be consistent with other page titles.

Then the error message (if there is an error message) can be displayed below the title inside a `p`.

Also, we can use one of the [Mozilla protocol buttons](https://protocol.mozilla.org/patterns/atoms/buttons.html). Neutral or secondary styles look good to me.

2022-05-25 23:25 UTC, BrianL3 commented
Great suggestions To. Neel, super pleased to see your work 👍

2022-05-25 23:26 UTC, BrianL3 approved these changes
I paired with Neel this afternoon!  Great fun, glad he's on the project.

2022-05-26 04:56 UTC, JacksonMaxfield reviewed
So happy this is in! Agree with To that we should try to use a mozilla styled button but otherwise. I am pretty happy with this. I leave code comments to To and Brian

2022-05-26 18:27 UTC, tohuynh approved these changes
Thanks for making the changes.

2022-05-26 18:27 UTC, merged